theme = "custom"

[editor]
cursorline = true
true-color = true
color-modes = false

[editor.statusline]
right = ["diagnostics", "selections", "position","position-percentage", "file-encoding"]


[keys.normal]
C-right = "move_next_word_start"
C-left = "move_prev_word_start"
d = ["extend_to_line_bounds", "yank", "yank_to_clipboard", "delete_selection"]
y = ["extend_to_line_bounds", "yank", "yank_to_clipboard"]
C-s = ":w"
C-q = ":quit"

[keys.insert]
C-right = "move_next_word_start"
C-left = "move_prev_word_start"

[keys.select]
y = ["extend_to_line_bounds", "yank", "yank_to_clipboard"]
d = ["extend_to_line_bounds", "yank", "yank_to_clipboard", "delete_selection"]
