[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
lineLength = 80

[[language]]
name = "python"
language-servers = ["ruff", "ty"]
auto-format = true
roots = ["pyproject.toml", "uv.lock", ".venv/"]
comment-token = "#"
