env:
  TERM: xterm-256color

window:
  padding:
    x: 8
    y: 8

  dynamic_padding: false
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 5000

# Font configuration
font:
  normal:
    family: FiraMono Nerd Font
    style: Regular

  bold:
    family: FiraMono Nerd Font
    style: Bold

  italic:
    family: FiraMono Nerd Font
    style: Italic

  bold_italic:
    family: FiraMono Nerd Font
    style: Bold Italic

  size: 11

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 1
    y: 1

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: false

# Sonokai (shusia)
# colors:
#   primary:
#     background: "0x2d2a2e"
#     foreground: "0xe3e1e4"

#   normal:
#     black: "0x1a181a"
#     red: "0xf85e84"
#     green: "0x9ecd6f"
#     yellow: "0xe5c463"
#     blue: "0x7accd7"
#     magenta: "0xab9df2"
#     cyan: "0xef9062"
#     white: "0xe3e1e4"

#   bright:
#     black: "0x1a181a"
#     red: "0xf85e84"
#     green: "0x9ecd6f"
#     yellow: "0xe5c463"
#     blue: "0x7accd7"
#     magenta: "0xab9df2"
#     cyan: "0xef9062"
#     white: "0xe3e1e4"

# Catppuccin!
colors:
  # Default colors
  primary:
    background: '0x1E1D2F'
    foreground: '0xD9E0EE'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1E1D2F'
    cursor: '0xF5E0DC'

  # Normal colors
  normal:
    black:   '0x6E6C7E'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan:    '0x89DCEB'
    white:   '0xD9E0EE'

  # Bright colors
  bright:
    black:   '0x988BA2'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan:    '0x89DCEB'
    white:   '0xD9E0EE'

  indexed_colors:
    - { index: 16, color: '0xF8BD96' }
    - { index: 17, color: '0xF5E0DC' }

window.opacity: 1.0

 # When set to `true`, selected text will be copied to the primary clipboard.
save_to_clipboard: true

# Allow terminal applications to change Alacritty's window title.
dynamic_title: true

mouse:
  hints:
    launcher:
      program: firefox
      args: []

key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: Insert,    mods: Shift,         action: PasteSelection              }
  - { key: Key0,      mods: Control,       action: ResetFontSize               }
  - { key: Equals,    mods: Control,       action: IncreaseFontSize            }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: F11,       mods: None,          action: ToggleFullscreen            }
  - { key: Paste,     mods: None,          action: Paste                       }
  - { key: Copy,      mods: None,          action: Copy                        }
  - { key: L,         mods: Control,       action: ClearLogNotice              }
  - { key: L,         mods: Control,       chars: "\x0c"                       }
  - { key: PageUp,    mods: None,          action: ScrollPageUp                }
  - { key: PageDown,  mods: None,          action: ScrollPageDown              }
  - { key: Home,      mods: Shift,         action: ScrollToTop                 }
  - { key: End,       mods: Shift,         action: ScrollToBottom              }

